var corpus = {
  "verbs": [
    "invest",
    "divest",
    "rollover",
    "sell",
    "buy",
    "purchase",
    "research",
    "crash",
    "amortize",
    "appraise",
    "Inflate",
    "deflate",
    "audit",
    "clean up",
    "appreciate",
    "depreciate",
    "incur",
    "inherit",
    "obligate",
    "open",
    "close",
    "capitalize",
    "expense",
    "transfer",
    "recover",
    "reserve",
    "generate",
    "review",
    "subordinate",
    "undesignate",
    "liquidate",
    "Release",
    "Shunt",
    "Reissue",
    "Issue"
  ],
  "nouns": [
    "DOW industrial index",
    "cash dividend",
    "stock dividend",
    "401k",
    "403b",
    "Roth IRA",
    "IRA",
    "Stocks",
    "Bonds",
    "assets",
    "capital",
    "cash",
    "checking account",
    "savings account",
    "index fund",
    "mutual fund",
    "ETF",
    "certificate of deposit",
    "retirement",
    "mortgage",
    "collateral",
    "closing fee",
    "contingency",
    "ROI",
    "equity",
    "expenses",
    "debt",
    "debit",
    "contract",
    "good faith estimate",
    "allotment",
    "promissory note",
    "profit and loss statement",
    "Arbitrage",
    "Appropriation of Profits",
    "Bear Market",
    "Blue Chip Securities",
    "triple net lease",
    "Underwriter",
    "Scrip",
    "Unissued scrip",
    "Unmarketable Parcel",
    "T + 3",
    "Tenancy in Common",
    "Tranche",
    "Section 1071B",
    "Sequestration Order",
    "Statutory Declaration",
    "Stock Exchange",
    "Sub Position",
    "Substantial Shareholder Notice (SSN)",
    "Synthetic Instrument",
    "Renounceable Rights",
    "Reserve Capital",
    "Residency Indicator",
    "Residual Cash Balance"
  ],
  "lessons": [
    "Funding your employer's 401k is a good idea.",
    "The yearly contribution limit to an IRA is $5,500.",
    "It's important to set aside three months of expenses in an emergency fund."
  ]
}